### ISSUE TITLE
Prepare Getting Started with MELODIES Tutorial

### ISSUE THREAD

**Issue by dwfncar** [NCAR/melodies#6]
For Monday, June 17 10 AM
FL0-2108private-ACD-2nd-Fl-CR

**Comment by dwfncar** [comment]
Encountering MONETIO issues with WRF reader.
Will gather python environment info and submit but reports ...

/home/fillmore/Data/WRF/wrfout_hourly_d02*
**** Reading WRF-Chem model output...
Traceback (most recent call last):
  File "/home/fillmore/EarthSystem/Tutorial/run_wrfchem.py", line 10, in <module>
    an.open_models()
  File "/home/fillmore/miniconda3/envs/melodies-monet/lib/python3.11/site-packages/melodies_monet-0.1.dev1-py3.11.egg/melodies_monet/driver.py", line 685, in open_models
  File "/home/fillmore/miniconda3/envs/melodies-monet/lib/python3.11/site-packages/melodies_monet-0.1.dev1-py3.11.egg/melodies_monet/driver.py", line 363, in open_model_files
  File "/home/fillmore/miniconda3/envs/melodies-monet/lib/python3.11/site-packages/monetio/models/_wrfchem_mm.py", line 192, in open_mfdataset
    dset = dset.reset_coords(["XTIME", "datetime"], drop=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fillmore/miniconda3/envs/melodies-monet/lib/python3.11/site-packages/xarray/core/dataset.py", line 2149, in reset_coords
    self._assert_all_in_dataset(names)
  File "/home/fillmore/miniconda3/envs/melodies-monet/lib/python3.11/site-packages/xarray/core/dataset.py", line 5813, in _assert_all_in_dataset
    raise ValueError(
ValueError: These variables cannot be found in this dataset: ['XTIME']



/home/fillmore/Data/WRF/wrfout_hourly_d02*
**** Reading WRF-Chem model output...
something happened opening file: Can not use auto rechunking with object dtype. We are unable to estimate the size in bytes of object data
Traceback (most recent call last):
  File "/home/fillmore/EarthSystem/Tutorial/run_wrfchem.py", line 20, in <module>
    an.pair_data()
  File "/home/fillmore/miniconda3/envs/melodies-monet/lib/python3.11/site-packages/melodies_monet-0.1.dev1-py3.11.egg/melodies_monet/driver.py", line 762, in pair_data
  File "/home/fillmore/miniconda3/envs/melodies-monet/lib/python3.11/site-packages/melodies_monet-0.1.dev1-py3.11.egg/melodies_monet/driver.py", line 254, in obs_to_df
AttributeError: 'NoneType' object has no attribute 'to_dataframe'

**Comment by dwfncar** [comment]
Scheduled for 2024 August 21 10 AM MST.  Pablo and Rebecca will help prepare.
